# Generated by Django 2.0.7 on 2018-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
