# Generated by Django 2.0.7 on 2018-11-08 14:46

import django.core.files.storage
from django.db import migrations, models
import slt.models


class Migration(migrations.Migration):

    dependencies = [
        ('slt', '0005_auto_20181108_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/pictures/', location='C:\\dev2\\wexfordslt\\media/pictures/'), upload_to=slt.models.image_directory_path),
        ),
    ]
