# Generated by Django 2.0.7 on 2018-11-09 10:43

import django.core.files.storage
from django.db import migrations, models
import slt.models


class Migration(migrations.Migration):

    dependencies = [
        ('slt', '0008_auto_20181109_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/slt/', location='C:\\dev2\\wexfordslt\\slt/'), upload_to=slt.models.image_directory_path),
        ),
    ]
