# Generated by Django 2.0.7 on 2018-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slt', '0009_auto_20181109_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
        ),
    ]
